---
title: "Stat 419 Final Project"
author: "Sumanth, Abby, Jett, Alex, Chris"
format: html
editor: visual
execute:
  echo: true
  warning: false
  message: false
---

```{r packages, echo=FALSE}
library(tidyverse)
library(here)
library(janitor)
library(knitr)
source(here("all_custom_functions.R"))
```

```{r data}
cincy <- read_csv(here("data", "cincy.csv")) |> clean_names()
cincy$pricerank <- as.factor(cincy$pricerank)

```

## Discriminant and Classification Analysis

### Correlated Quantitative Variables

```{r}
kable(cor(cincy |> select(-pricerank)))
```

```{r}
plot(cincy[,2:7])
```

It appears that quality and area, along with bathroom and area have the highest correlations. These may be omitted from analysis.

<!-- Flagged by Jett. Above needs better justification and should also cite the correlations -->

### Discriminant Analysis

```{r}
# First remove whatever variables had multicollinearity above
# Can't get this working for some reaosn. I tried making pricerank a factor? 
discrim(cincy[,-1], cincy$pricerank)
```

### Classification Analysis
